server:
  port: 8083
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: root
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  config:
    import: optional:configserver:http://localhost:8085